### ISSUE TITLE
Hardcoded scripts folder name causes script to fail

### ISSUE THREAD

**Issue by Marc-Winner** [acendan/reascripts#2]
Error when running script acendan_reaperblog_Duplicate items or tracks depending on focus and time selection.lua:
"This script requires ACendan Lua Utilities! Please install them here:
Extensions > ReaPack > Browse Packages > 'ACendan Lua Utilities'"
I had Lua Utilities installed and error persisted.

Going to the source I found that path to scripts was written with lowercase S:
reaper.GetResourcePath()..'/**s**cripts/ACendan Scripts/Development/acendan_Lua Utilities.lua'
both in acendan_Lua Utilities.lua and acendan_reaperblog_Duplicate items or tracks depending on focus and time selection.lua.

I changed "scripts" for "Scripts" everywhere and the script worked.
Please, change the path by default, make case-insensitive folder seeker or add a mention of this in docs to repo.

Thank you for the script, it is awesome!

**Comment by acendan** [comment]
Hi @Marc-Winner, 

Thanks for letting me know about this issue! Out of curiosity, what platform/operating system are you on? You're the first person to report having this problem to me; which is a bit of a surprise.

Cheers!

**Comment by acendan** [comment]
Hey Marc! Recently I set up a Linux Virtual Machine for the first time and ran into the same issue you mentioned. Just pushed out an update to all of my scripts that referred to the lowercase path. Should hopefully work as expected now!

**Comment by Marc-Winner** [comment]
Glad to hear it!

Keep up the good work!


Best regards,
Marsel

**Comment by Marc-Winner** [comment]
Hello,

I use Ubuntu 21.04. Yeah, I don't know how naming of folders change from OS
to OS. Maybe, other users are just so advanced that they corrected it
silently)

Best,
Marsel
